CREATE TABLE console
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    command     VARCHAR(255)                             NOT NULL,
    result      VARCHAR(255)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_console PRIMARY KEY (id)
);

CREATE TABLE conversation
(
    id             UUID         NOT NULL,
    initiator_name VARCHAR(255) NOT NULL,
    receiver_name  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_conversation PRIMARY KEY (id)
);

CREATE TABLE message
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(64),
    message         VARCHAR(1024)                            NOT NULL,
    reply_id        INTEGER                                  NOT NULL,
    date            BIGINT                                   NOT NULL,
    conversation_id UUID                                     NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

CREATE TABLE token_table
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    access_token  VARCHAR(255)                            NOT NULL,
    refresh_token VARCHAR(255)                            NOT NULL,
    is_logged_out BOOLEAN                                 NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_token_table PRIMARY KEY (id)
);

CREATE TABLE users_table
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(64)                             NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    role          VARCHAR(16)                             NOT NULL,
    display_name  VARCHAR(64),
    bio           VARCHAR(1024),
    profile_image VARCHAR(255),
    CONSTRAINT pk_users_table PRIMARY KEY (id)
);

ALTER TABLE users_table
    ADD CONSTRAINT uc_users_table_email UNIQUE (email);

ALTER TABLE users_table
    ADD CONSTRAINT uc_users_table_username UNIQUE (username);

ALTER TABLE token_table
    ADD CONSTRAINT FK_TOKEN_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES users_table (id);